title: About StyleShare
email: dev@stylesha.re
url: http://about.stylesha.re
hiring: false
title: "StyleShare inc."
description: "우리는 무엇을 입을지 고민하는 사람과, 좋은 옷에 대한 경험을 나누고자 하는 사람을 연결합니다."

highlighter: pygments
markdown: redcarpet
gems:
  - jekyll-sitemap

sass:
  style: compressed
